import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { env } from "../env.js";

// Document generation sits behind this interface so the workflow doesn't
// depend on which backend produces the PDF.
//
// `local` renders a real PDF with pdf-lib to local disk. It is the dev/demo
// path and produces a genuine, inspectable document — not a placeholder — but
// it renders a generated summary page rather than filling the GP's actual
// uploaded PDF, because filling arbitrary AcroForm fields keyed by Anvil's
// field ids only makes sense once those ids come from Anvil.
//
// `anvil` is the production path: POST the resolved values to
// https://app.useanvil.com/api/v1/fill/{pdfTemplateID}.pdf, which returns the
// filled PDF as binary. That call is confirmed from Anvil's docs, but it is
// unimplemented here because it can't be exercised without an API key — and a
// fill call written blind against an unverified field-key contract is exactly
// the thing that would silently produce wrong documents. It throws a clear
// error rather than pretending.

export interface FillRequest {
  subscriptionId: string;
  tenantId: string;
  anvilTemplateId: string;
  originalFilename: string;
  /** anvilFieldKey → resolved value, from resolveFields(). */
  values: Record<string, string>;
  /** Display context for the local renderer. */
  context: {
    fundName: string;
    investorName: string;
    fieldLabels: Record<string, string>;
  };
}

export interface FillResult {
  storagePath: string;
  provider: "local" | "anvil";
}

export interface DocumentProvider {
  kind: "local" | "anvil";
  fill(req: FillRequest): Promise<FillResult>;
}

const localProvider: DocumentProvider = {
  kind: "local",
  async fill(req) {
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([612, 792]); // US Letter
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

    const margin = 56;
    let y = 792 - margin;

    const draw = (text: string, opts: { size?: number; bold?: boolean; gap?: number } = {}) => {
      const size = opts.size ?? 10;
      page.drawText(text, {
        x: margin,
        y,
        size,
        font: opts.bold ? bold : font,
        color: rgb(0.1, 0.11, 0.14),
      });
      y -= (opts.gap ?? size + 8);
    };

    draw("SUBSCRIPTION AGREEMENT", { size: 16, bold: true, gap: 10 });
    draw(req.context.fundName, { size: 12, bold: true, gap: 22 });

    page.drawLine({
      start: { x: margin, y: y + 8 },
      end: { x: 612 - margin, y: y + 8 },
      thickness: 0.75,
      color: rgb(0.8, 0.81, 0.85),
    });
    y -= 12;

    draw("SUBSCRIBER DETAILS", { size: 9, bold: true, gap: 18 });

    for (const [key, value] of Object.entries(req.values)) {
      const label = req.context.fieldLabels[key] ?? key;
      page.drawText(`${label}:`, {
        x: margin,
        y,
        size: 9,
        font,
        color: rgb(0.42, 0.45, 0.5),
      });
      page.drawText(value, { x: margin + 190, y, size: 10, font: bold, color: rgb(0.1, 0.11, 0.14) });
      y -= 20;
    }

    y -= 16;
    page.drawLine({
      start: { x: margin, y: y + 8 },
      end: { x: 612 - margin, y: y + 8 },
      thickness: 0.75,
      color: rgb(0.8, 0.81, 0.85),
    });
    y -= 12;

    draw("SIGNATURES", { size: 9, bold: true, gap: 20 });
    draw("Subscriber: ______________________________   Date: ____________", { size: 10, gap: 26 });
    draw("General Partner: _________________________   Date: ____________", { size: 10, gap: 26 });

    y -= 10;
    page.drawText(
      `Generated by Alta from template "${req.originalFilename}" (${req.anvilTemplateId}).`,
      { x: margin, y, size: 7.5, font, color: rgb(0.55, 0.58, 0.63) }
    );
    y -= 11;
    page.drawText(
      "DEV/DEMO DOCUMENT — rendered locally, not produced by the Anvil PDF-fill API.",
      { x: margin, y, size: 7.5, font, color: rgb(0.55, 0.58, 0.63) }
    );

    const bytes = await pdf.save();
    const dir = path.join(env.UPLOAD_ROOT, req.tenantId, "subscriptions", req.subscriptionId);
    fs.mkdirSync(dir, { recursive: true });
    const storagePath = path.join(dir, `${randomUUID()}.pdf`);
    fs.writeFileSync(storagePath, bytes);

    return { storagePath, provider: "local" };
  },
};

const anvilProvider: DocumentProvider = {
  kind: "anvil",
  async fill() {
    throw new Error(
      "Anvil fill provider is not implemented. The endpoint is confirmed " +
        "(POST https://app.useanvil.com/api/v1/fill/{pdfTemplateID}.pdf) but the " +
        "field-key contract depends on Anvil's detected-field response shape, " +
        "which is still unverified. Set DOCUMENT_PROVIDER=local for dev."
    );
  },
};

export function getDocumentProvider(): DocumentProvider {
  return process.env.DOCUMENT_PROVIDER === "anvil" ? anvilProvider : localProvider;
}
