// GENERATED from the Open Disclosure project (~/dev/advisorapp), which builds
// on SEC Form ADV Schedule D 7.B.(1) private-fund reporting.
//
// Real, as-filed: fund name, fund type, domicile, gross asset value, the
// Investment Company Act exclusion (3(c)(1) vs 3(c)(7)), and master/feeder
// status.
//
// Synthetic, because ADV reports neither: minInvestment and closeDate.
//
// `advFundType` is carried verbatim alongside Alta's `vehicleType` because the
// two taxonomies do not line up — Alta's enum was invented before this data
// existed and has no member for hedge, securitized-asset, or liquidity funds.
// Keeping the real value means the mapping stays auditable instead of lossy.

export interface SeedFund {
  name: string;
  legalName: string;
  vehicleType: 'lp' | 'llc_feeder' | 'interval_fund' | 'non_traded_bdc' | 'evergreen';
  structure: 'drawdown' | 'continuous';
  minInvestment: number;
  closeDate: string | null;
  gpSignatoryName: string;
  /** ADV fund_type, verbatim — the real taxonomy vehicleType approximates. */
  advFundType: string;
  domicile: string;
  /** 3c1 = accredited investors OK; 3c7 = qualified purchasers only. */
  exclusion: '3c1' | '3c7' | null;
  isMasterFund: boolean;
  isFeederFund: boolean;
  grossAssetValueUsd: number;
}

export interface SeedSponsor {
  slug: string; name: string; gpEmail: string;
  gpFirstName: string; gpLastName: string; funds: SeedFund[];
}

export const SEED_SPONSORS: SeedSponsor[] = [
  {
    slug: "goldman-sachs-asset-management-l-p",
    name: "Goldman Sachs Asset Management, L.P.",
    gpEmail: "gpops@goldman.test",
    gpFirstName: "Priya", gpLastName: "Nair",
    funds: [
      {
        name: "Exchange Place Master LP",
        legalName: "EXCHANGE PLACE MASTER LP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-03-31",
        gpSignatoryName: "Priya Nair",
        advFundType: "Other Private Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 12799849144,
      },
      {
        name: "Vintage IX B LP",
        legalName: "VINTAGE IX B LP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-06-30",
        gpSignatoryName: "Priya Nair",
        advFundType: "Other Private Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 9633319825,
      },
      {
        name: "West Street Strategic Solutions Offshore Fund I, L.P.",
        legalName: "WEST STREET STRATEGIC SOLUTIONS OFFSHORE FUND I, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-09-30",
        gpSignatoryName: "Priya Nair",
        advFundType: "Private Equity Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 7931788922,
      },
      {
        name: "Vintage VIII LP",
        legalName: "VINTAGE VIII LP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "Priya Nair",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 7718077574,
      },
    ],
  },
  {
    slug: "ares-management-llc",
    name: "Ares Management LLC",
    gpEmail: "gpops@ares.test",
    gpFirstName: "Daniel", gpLastName: "Okafor",
    funds: [
      {
        name: "Ares Senior Credit Master Fund III LP",
        legalName: "ARES SENIOR CREDIT MASTER FUND III LP",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Daniel Okafor",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 23210273397,
      },
      {
        name: "Ares Senior Direct Lending Master Fund II Designated Activity Company",
        legalName: "ARES SENIOR DIRECT LENDING MASTER FUND II DESIGNATED ACTIVITY COMPANY",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Daniel Okafor",
        advFundType: "Hedge Fund",
        domicile: "Ireland",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 12916740503,
      },
      {
        name: "Ares Capital Europe VI (E) II Levered, L.P.",
        legalName: "ARES CAPITAL EUROPE VI (E) II LEVERED, L.P.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Daniel Okafor",
        advFundType: "Hedge Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 9890543882,
      },
      {
        name: "Ares Capital Europe V (E) Levered",
        legalName: "ARES CAPITAL EUROPE V (E) LEVERED",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Daniel Okafor",
        advFundType: "Hedge Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 9801923132,
      },
    ],
  },
  {
    slug: "two-sigma-investments-lp",
    name: "Two Sigma Investments, LP",
    gpEmail: "gpops@twosigma.test",
    gpFirstName: "Sofia", gpLastName: "Marchetti",
    funds: [
      {
        name: "Two Sigma Absolute Return Portfolio, LLC",
        legalName: "TWO SIGMA ABSOLUTE RETURN PORTFOLIO, LLC",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Sofia Marchetti",
        advFundType: "Hedge Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 38337427187,
      },
      {
        name: "Two Sigma Spectrum Portfolio, LLC",
        legalName: "TWO SIGMA SPECTRUM PORTFOLIO, LLC",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Sofia Marchetti",
        advFundType: "Hedge Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 37231961306,
      },
      {
        name: "Two Sigma Equity Portfolio, LLC",
        legalName: "TWO SIGMA EQUITY PORTFOLIO, LLC",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Sofia Marchetti",
        advFundType: "Hedge Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 21754330720,
      },
      {
        name: "Two Sigma Futures Portfolio, LLC",
        legalName: "TWO SIGMA FUTURES PORTFOLIO, LLC",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Sofia Marchetti",
        advFundType: "Hedge Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 21599006885,
      },
    ],
  },
  {
    slug: "apollo-capital-management-l-p",
    name: "Apollo Capital Management, L.P.",
    gpEmail: "gpops@apollo.test",
    gpFirstName: "James", gpLastName: "Whitlock",
    funds: [
      {
        name: "Apollo Aligned Alternatives Aggregator, L.P.",
        legalName: "APOLLO ALIGNED ALTERNATIVES AGGREGATOR, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-03-31",
        gpSignatoryName: "James Whitlock",
        advFundType: "Other Private Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 16694413528,
      },
      {
        name: "Apollo Aligned Alternatives (A), L.P.",
        legalName: "APOLLO ALIGNED ALTERNATIVES (A), L.P.",
        vehicleType: "llc_feeder", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-06-30",
        gpSignatoryName: "James Whitlock",
        advFundType: "Other Private Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: true,
        grossAssetValueUsd: 16690702951,
      },
      {
        name: "A-a Offshore (Aaa), L.P.",
        legalName: "A-A OFFSHORE (AAA), L.P.",
        vehicleType: "llc_feeder", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-09-30",
        gpSignatoryName: "James Whitlock",
        advFundType: "Other Private Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: true,
        grossAssetValueUsd: 13546688327,
      },
      {
        name: "Apollo Investment Fund IX, L.P.",
        legalName: "APOLLO INVESTMENT FUND IX, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "James Whitlock",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 10929220785,
      },
    ],
  },
  {
    slug: "kohlberg-kravis-roberts-co-l-p",
    name: "Kohlberg Kravis Roberts & Co. L.P.",
    gpEmail: "gpops@kkr.test",
    gpFirstName: "Amara", gpLastName: "Osei",
    funds: [
      {
        name: "KKR North America Fund XIII SCSP",
        legalName: "KKR NORTH AMERICA FUND XIII SCSP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-03-31",
        gpSignatoryName: "Amara Osei",
        advFundType: "Private Equity Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 21165504870,
      },
      {
        name: "KKR Asian Fund IV SCSP",
        legalName: "KKR ASIAN FUND IV SCSP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-06-30",
        gpSignatoryName: "Amara Osei",
        advFundType: "Private Equity Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 17135524813,
      },
      {
        name: "KKR Global Infrastructure Investors IV (Usd) SCSP",
        legalName: "KKR GLOBAL INFRASTRUCTURE INVESTORS IV (USD) SCSP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-09-30",
        gpSignatoryName: "Amara Osei",
        advFundType: "Private Equity Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 13138805532,
      },
      {
        name: "KKR Americas Fund XII L.P.",
        legalName: "KKR AMERICAS FUND XII L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "Amara Osei",
        advFundType: "Private Equity Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 13011814877,
      },
    ],
  },
  {
    slug: "point72-asset-management-l-p",
    name: "Point72 Asset Management, L.P.",
    gpEmail: "gpops@point72.test",
    gpFirstName: "Henrik", gpLastName: "Lindqvist",
    funds: [
      {
        name: "Point72 Associates, LLC",
        legalName: "POINT72 ASSOCIATES, LLC",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Henrik Lindqvist",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 266320056307,
      },
      {
        name: "Point72 Capital International, LTD.",
        legalName: "POINT72 CAPITAL INTERNATIONAL, LTD.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Henrik Lindqvist",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 32014110351,
      },
      {
        name: "Point72 Capital, L.P.",
        legalName: "POINT72 CAPITAL, L.P.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Henrik Lindqvist",
        advFundType: "Hedge Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 11324494524,
      },
      {
        name: "Point72 Turion Master, L.P.",
        legalName: "POINT72 TURION MASTER, L.P.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Henrik Lindqvist",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 4339105745,
      },
    ],
  },
  {
    slug: "carlyle-investment-management-l-l-c",
    name: "Carlyle Investment Management L.L.C.",
    gpEmail: "gpops@carlyle.test",
    gpFirstName: "Marcus", gpLastName: "Webb",
    funds: [
      {
        name: "Carlyle Partners VII",
        legalName: "CARLYLE PARTNERS VII",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-03-31",
        gpSignatoryName: "Marcus Webb",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 22219100000,
      },
      {
        name: "Carlyle Partners VIII",
        legalName: "CARLYLE PARTNERS VIII",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-06-30",
        gpSignatoryName: "Marcus Webb",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 14327860000,
      },
      {
        name: "Carlyle Realty Partners IX",
        legalName: "CARLYLE REALTY PARTNERS IX",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-09-30",
        gpSignatoryName: "Marcus Webb",
        advFundType: "Real Estate Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 7338861000,
      },
      {
        name: "Carlyle Property Investors, L.P.",
        legalName: "CARLYLE PROPERTY INVESTORS, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "Marcus Webb",
        advFundType: "Real Estate Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 6960289000,
      },
    ],
  },
  {
    slug: "blackstone-management-partners-l-l-c",
    name: "Blackstone Management Partners L.L.C.",
    gpEmail: "gpops@blackstone.test",
    gpFirstName: "Elena", gpLastName: "Kovacs",
    funds: [
      {
        name: "Blackstone Capital Partners VIII L.P.",
        legalName: "BLACKSTONE CAPITAL PARTNERS VIII L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-03-31",
        gpSignatoryName: "Elena Kovacs",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 31383450000,
      },
      {
        name: "Blackstone Capital Partners IX L.P.",
        legalName: "BLACKSTONE CAPITAL PARTNERS IX L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-06-30",
        gpSignatoryName: "Elena Kovacs",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 24619540000,
      },
      {
        name: "Blackstone Capital Partners VII L.P.",
        legalName: "BLACKSTONE CAPITAL PARTNERS VII L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-09-30",
        gpSignatoryName: "Elena Kovacs",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 16328040000,
      },
      {
        name: "Blackstone Capital Partners Asia III L.P.",
        legalName: "BLACKSTONE CAPITAL PARTNERS ASIA III L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "Elena Kovacs",
        advFundType: "Private Equity Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 8359647000,
      },
    ],
  },
  {
    slug: "thoma-bravo-l-p",
    name: "Thoma Bravo, L.P.",
    gpEmail: "gpops@thomabravo.test",
    gpFirstName: "Nathaniel", gpLastName: "Cross",
    funds: [
      {
        name: "Thoma Bravo Fund XV-A, L.P.",
        legalName: "THOMA BRAVO FUND XV-A, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-03-31",
        gpSignatoryName: "Nathaniel Cross",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 19130000000,
      },
      {
        name: "Thoma Bravo Fund XVI-A, L.P.",
        legalName: "THOMA BRAVO FUND XVI-A, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 500000, closeDate: "2027-06-30",
        gpSignatoryName: "Nathaniel Cross",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 13792300000,
      },
      {
        name: "Thoma Bravo Fund XV, L.P.",
        legalName: "THOMA BRAVO FUND XV, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-09-30",
        gpSignatoryName: "Nathaniel Cross",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 10618000000,
      },
      {
        name: "Thoma Bravo Fund XIV-A, L.P.",
        legalName: "THOMA BRAVO FUND XIV-A, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "Nathaniel Cross",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 10488100000,
      },
    ],
  },
  {
    slug: "hps-investment-partners-llc",
    name: "HPS Investment Partners, LLC",
    gpEmail: "gpops@hps.test",
    gpFirstName: "Yuki", gpLastName: "Tanaka",
    funds: [
      {
        name: "HPS Offshore Strategic Investment Partners V, L.P.",
        legalName: "HPS OFFSHORE STRATEGIC INVESTMENT PARTNERS V, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-03-31",
        gpSignatoryName: "Yuki Tanaka",
        advFundType: "Private Equity Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 6399123000,
      },
      {
        name: "HPS Specialty Loan International Fund VI-L, SCSP",
        legalName: "HPS SPECIALTY LOAN INTERNATIONAL FUND VI-L, SCSP",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Yuki Tanaka",
        advFundType: "Hedge Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 5426192000,
      },
      {
        name: "HPS Strategic Investment Partners V, L.P.",
        legalName: "HPS STRATEGIC INVESTMENT PARTNERS V, L.P.",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-09-30",
        gpSignatoryName: "Yuki Tanaka",
        advFundType: "Private Equity Fund",
        domicile: "Delaware",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 5368555000,
      },
      {
        name: "Core Senior Lending Portfolio II, SCSP",
        legalName: "CORE SENIOR LENDING PORTFOLIO II, SCSP",
        vehicleType: "lp", structure: "drawdown",
        minInvestment: 250000, closeDate: "2027-12-31",
        gpSignatoryName: "Yuki Tanaka",
        advFundType: "Private Equity Fund",
        domicile: "Luxembourg",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 4790582000,
      },
    ],
  },
  {
    slug: "citadel-advisors-llc",
    name: "Citadel Advisors LLC",
    gpEmail: "gpops@citadel.test",
    gpFirstName: "Isabella", gpLastName: "Moreau",
    funds: [
      {
        name: "Citadel Global Fixed Income Master Fund Ltd.",
        legalName: "CITADEL GLOBAL FIXED INCOME MASTER FUND LTD.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Isabella Moreau",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 331320200000,
      },
      {
        name: "GFIL Holdings Ltd.",
        legalName: "GFIL HOLDINGS LTD.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Isabella Moreau",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 290469100000,
      },
      {
        name: "Citadel Multi-Strategy Equities Master Fund Ltd.",
        legalName: "CITADEL MULTI-STRATEGY EQUITIES MASTER FUND LTD.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Isabella Moreau",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 92049210000,
      },
      {
        name: "CEMF Holdings Ltd.",
        legalName: "CEMF HOLDINGS LTD.",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Isabella Moreau",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: false, isFeederFund: false,
        grossAssetValueUsd: 81177680000,
      },
    ],
  },
  {
    slug: "millennium-management-llc",
    name: "Millennium Management LLC",
    gpEmail: "gpops@millennium.test",
    gpFirstName: "Connor", gpLastName: "Doyle",
    funds: [
      {
        name: "Millennium Partners, L.P.",
        legalName: "MILLENNIUM PARTNERS, LP",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Connor Doyle",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 687662000000,
      },
      {
        name: "WMQS Global Equity Active Extension Master Fund LP",
        legalName: "WMQS GLOBAL EQUITY ACTIVE EXTENSION MASTER FUND LP",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Connor Doyle",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 12756180000,
      },
      {
        name: "WMA Systematic Equity Alpha Long/Short Master Fund LP",
        legalName: "WMA SYSTEMATIC EQUITY ALPHA LONG/SHORT MASTER FUND LP",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Connor Doyle",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 3218479000,
      },
      {
        name: "WMA US Active Extension Master Fund LP",
        legalName: "WMA US ACTIVE EXTENSION MASTER FUND LP",
        vehicleType: "evergreen", structure: "continuous",
        minInvestment: 1000000, closeDate: null,
        gpSignatoryName: "Connor Doyle",
        advFundType: "Hedge Fund",
        domicile: "Cayman Islands",
        exclusion: '3c7',
        isMasterFund: true, isFeederFund: false,
        grossAssetValueUsd: 2752445000,
      },
    ],
  },
];
